baseurl: /Python-Kurs2015
highlighter: pygments

title: Python-Kurs 2015
description: Unterlagen und Programme für den Python Kurs
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate
include: ['kurstage']

